[workspace]
resolver = "1"
members = ["./chat-p0c"]

[workspace.dependencies]
bs58 = "0.5.0"
camino = "1.1.6"
clap = "4.4.18"
color-eyre = "0.6.2"
const_format = "0.2.31"
dirs = "5.0.1"
libp2p = "0.53.2"
serde = "1.0.196"
tokio = "1.35.1"
toml = "0.8.9"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
