[package]
name = "chat-p0c"
version = "0.1.0"
edition = "2021"

[dependencies]
bs58.workspace = true
camino.workspace = true
clap = { workspace = true, features = ["env", "derive"] }
color-eyre.workspace = true
dirs.workspace = true
jsonrpc = "0.17.0"
jsonrpc-core = "18.0.0"
jsonrpc-http-server = "18.0.0"
libp2p = { workspace = true, features = ["full"] }
serde.workspace = true
tokio = { workspace = true, features = ["io-std", "macros"] }
toml.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
